### ISSUE TITLE
Add more links

### ISSUE THREAD

**Issue by tyteen4a03** [WhataShane/save418#4]
See https://github.com/aspnet/HttpAbstractions/issues/915 and https://github.com/requests/requests/issues/4238

**Comment by WhataShane** [comment]
I'm on it.

**Comment by tyteen4a03** [comment]
Just saw a73c6af, `requests` is not a part of the Python standard library.

**Comment by tyteen4a03** [comment]
Owner of requests has shot down the proposal: https://github.com/requests/requests/issues/4238#issuecomment-321705847

**Comment by WhataShane** [comment]
Woohoo! Everything should be current now.
