### ISSUE TITLE
Please be more respectful

### ISSUE THREAD

**Issue by sebdeckers** [WhataShane/save418#5]
The website's use of "conniving contributor" implies secrecy and ill intent. This is completely wrong and disrespectful.

In case you are not aware, Mark Nottingham (@mnot) has made countless contributions to many standards (HTTP-related). All of this work is done on the public record. Please show the man respect even if you disagree with his position on this particular issue.

Also, IETF/IANA have clearly defined and battle-tested processes to debate issues on merit. Resorting to slander is not productive. Waging social media campaigns (HN brigading, etc) is mostly spam and detracts from any merit in your argument.

**Comment by WhataShane** [comment]
I disagree. "Conniving" in this use case is clearly hyperbole. I mean, we're talking about an error code originally implemented as a joke on April 1st in 1998 . I understand @mnot is a long standing, well respected, and valuable contributor to the HTTP community, and I have only the utmost respect for him myself. I disagree that it detracts from the argument. I feel it adds a touch of light-heartedness to the site. A person trying to change an HTTP error code clearly isn't "conniving" - they're more like a cartoony mad scientist villain who machinates to rid the world of fun.

**Comment by mnot** [comment]
FWIW, I'm fine with it -- it's clearly tongue-in-cheek. My goal in all of this was to clarify the status of the code (it had previously been asserted that no one would care about 418, and that's clearly not true). We've done that admirably.

There are a few comments here and there that are much more personal, but that's just the sad state of our community showing its ugly face.
