### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by mnot** [WhataShane/save418#7]
Please update the site to use HTTPS (with HSTS, etc.); it's just good practice.

**Comment by WhataShane** [comment]
Github Pages doesn't seem to allow HTTPS on custom domains. I was looking into using [Cloudflare's "Universal SSL"](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/), although it seems as though such an implementation would only be a boon to search engine ranking; although I very well could be mistaken. Please let me know if this isn't the case.

**Comment by mnot** [comment]
Ah, that's right.

**Comment by TPS** [comment]
Now HTTPS!
